server:
  port: 8080

spring:
  application:
    name: "大名商城"
  datasource:
    url: jdbc:mysql://47.101.176.115:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
  redis:
    host: 47.101.176.115
    database: 0 #redis数据库索引 默认是0
    port: 6379
    password: huyangxuan2580
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
  data:
    elasticsearch:
      repositories:
        enabled: false
    mongodb:
      host: 47.101.176.115
      port: 27017
      database: mall-port
      username: root
      password: root123
  rabbitmq:
    host: 47.101.176.115 # rabbitmq的连接地址
    port: 5672 # rabbitmq的连接端口号
    virtual-host: /mall # rabbitmq的虚拟host
    username: admin # rabbitmq的用户名
    password: admin123 # rabbitmq的密码
#    publisher-confirms: true #如果对异步消息需要回调必须设置为true
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  applicationName: ${spring.application.name}
  applicationVersion: 1.0
  applicationDescription: springfox swagger 3.0整合Demo
  tryHost: http://localhost:${server.port}

# 自定义redis key
redis:
  key:
    prefixAuthCode: "portal:authCode:"
    expireAuthCode: 120 # 验证码超期时间

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

es:
  address: 47.101.176.115
  port: 9200
  username:
  password:
